### ISSUE TITLE
Link-neuron matching with hemibrainr

### ISSUE THREAD

**Issue by tedwu-neuro** [natverse/neuronbridger#1]
Hi,

Could you please put the link for this ("neuron matching with hemibrainr"), and I am thinking to do the similar thing, which is to find  corresponding neurons from my own experiment in neuprint.

Thanks in advance!

Best,
Yifan

**Comment by jefferis** [comment]
Dear @tedwu-neuro, thanks for your interest. Could you just specify what the source and target for the link would be? For example by saying which URL should contain the link and which URL it should be point to?

**Comment by tedwu-neuro** [comment]
Thanks for your reply.

I think it's this one (https://flyconnectome.github.io/hemibrainr/articles/match_making.html)

I got it from this page: https://github.com/natverse/neuronbridger/
------
"NBLAST can also be used to match EM and LM neurons. However, it works best with ‘skeletonised’ neurons. Using ‘colour depth mask search’ circumvents this ‘skeletonisation’ step for both volumetric EM data and LM data. This step is still non-trivial. We have used NBLAST to match skeletons between two EM dataset, see: neuron matching with hemibrainr."

What I want to do is to find the neuron in neuprint, which matched with the neuron from my experiment. Can I use the link I asked as an instruction?

Best,
Yifan

**Comment by alexanderbates** [comment]
Thank you for flagging. That repository moved, and the new location for the document is: https://natverse.github.io/hemibrainr/articles/match_making.html

I have updated the README. Note that running the matching pipeline is describes requires access to a google drive for data that is currently private, in order to run optimally. Hopefully, at some point in the future we can make it public, but right now it is data that is being actively built and is in flux.
